[BUGFIX] Fix multiple issues with input and output (#13)

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -1,8 +1,17 @@
 #!/bin/bash
 
+# load the .env file
+ENV_FILE="./.env"
+
+if [ -f "$ENV_FILE" ]; then
+  export $(grep -v '^#' $ENV_FILE | xargs)
+else
+  echo ".env file not found! Exiting..."
+  exit 1
+fi
+
 # set variables
 PACKAGE=$1
-VERSION='0.03'
 BUILD=$(git rev-parse --short HEAD)
 DIR="build"
 
@@ -36,12 +45,12 @@ do
       fi
 
       # build the Go executable
-      env GOOS="$GOOS" GOARCH="$GOARCH" go build -ldflags="-X './app/cmd/root.version=${VERSION}' -X './app/cmd/root.build=${BUILD}'" -o ./$DIR/$package_name ./app/
+      env GOOS="$GOOS" GOARCH="$GOARCH" go build -ldflags="-X './config.version=${VERSION}' -X './config.build=${BUILD}'" -o ./$DIR/$package_name ./cmd/
       wait
 
       # TAR the files
       echo "Tarring the file: $package_name"
-      tar -czvf ./$DIR/"${output_name}.tar.gz" ./$DIR/$package_name
+      tar -czvf ./$DIR/"${output_name}.tar.gz" -C $DIR $package_name
       wait
 
       # remove the non packaged binary file
